### ISSUE TITLE
Attaching document (image / png ) with xelatex kernel doesn't not work

### ISSUE THREAD

**Issue by SebastienHo** [ho-tex/attachfile2#5]
Hi,

I use latest miktek console (4.5) with all packages updated to generate a pdf with xelatex command.

It my pdf, I need to embed some doc (such as pictures / url and pdf). In the output pdf, I have a document attached but it is embedded as : "þÿ"

here is a sample code: 

`
      \documentclass[a4paper, 11pt]{article}
      %Use longtatle
      %Attach file package
      \usepackage{attachfile2}
    \begin{document}  
		
        % Section 3 - Technical sheet attachment

        \section{Pièces jointes / Fiches techniques}
        \begin{itemize}
                           
            \item[$\bullet$] \texorpdfstring{Dessin coté}{} \attachfile[description={\texorpdfstring{Dim\_ B.gif}{}}, icon={Paperclip}]{./d3f20a1d-1075-483a-a7a4-01b0a5fe63b24.png}
				
        \end{itemize}
    
      \end{document}
`
[rampa_002614001.pdf](https://github.com/ho-tex/attachfile2/files/7761453/rampa_002614001.pdf)
![d3f20a1d-1075-483a-a7a4-01b0a5fe63b24](https://user-images.githubusercontent.com/3601250/147067671-c26114d8-fb85-41a7-9111-dbcec88ffc52.png)

Can you help?

**Comment by u-fischer** [comment]
I will have to check why the encoding is wrong later. For now try `ucfilespec=d3f20a1d-1075-483a-a7a4-01b0a5fe63b24.png`

**Comment by SebastienHo** [comment]
Thanks I'll test this way and keep you updated

**Comment by czakey** [comment]
This doesn't also work with attaching plain .pdf (without any special chars in name) files. Behaviour is same.

**Comment by u-fischer** [comment]
@czakey  "it doesn't work" is not a sensible problem description. Did you try the work around to set the ucfilespec?

**Comment by czakey** [comment]
> @czakey "it doesn't work" is not a sensible problem description. Did you try the work around to set the ucfilespec?

Sorry. Yes, it works with that workaround.

**Comment by davidcarlisle** [comment]
This will be released to ctan in version 2.12
