### ISSUE TITLE
Typo in documentation: "Options `file` and `nofile`"

### ISSUE THREAD

**Issue by user202729** [ho-tex/attachfile2#7]
https://github.com/ho-tex/attachfile2/blob/660cea7a9870822a21caec939986087f9a794367/attachfile2.dtx#L306-L307

The option names should be `nofiles` I believe. On the other hand both `file` and `files` option does not exist.

(remark: also change in https://tex.stackexchange.com/a/182645/250119 if possible)

**Comment by davidcarlisle** [comment]
thanks for the report.

**Comment by user202729** [comment]
Actually that fix isn't right either, there's no `files` option either. Only `nofiles`.

**Comment by davidcarlisle** [comment]
> Actually that fix isn't right either, there's no `files` option either. Only `nofiles`.

sigh I swear I checked the option names before making the change but yes.

**Comment by davidcarlisle** [comment]
@u-fischer there are two open issues that you've commented on, anything do-able before a release (not sure if it's worth a release just for this doc fix, perhaps it  is?)

**Comment by u-fischer** [comment]
@davidcarlisle  issue #5 is resolved in the code and would probably warant a release. issue #2 would need more thinking.

**Comment by davidcarlisle** [comment]
@u-fischer  thanks, so we could close 5, leave 2 to another day but push out the current head as a release to ctan?

**Comment by u-fischer** [comment]
@davidcarlisle yes
