### ISSUE TITLE
How to use `date` option?

### ISSUE THREAD

**Issue by epilys** [ho-tex/attachfile2#9]
I'd like to override the mod/creation time of a file by setting the `date` option, but I cannot figure out the correct format.

**Comment by u-fischer** [comment]
Do not use the issue tracker for general support. Ask such questions on sites like tex.stackexchange (and then provide a complete minimal example). 

As mentioned in the attachfile2 documentation its commands and options are based on the attachfile package:

> Basically this package attachfile2 follows the user interface of package attachfile,
look into its documentation.

Date usage is described in section 4.2 of the attachfile documentation.
